import { NextResponse } from "next/server";
import { verifySchoolAdmin } from "@/lib/school-auth";
import { getServiceClient } from "@/lib/supabase/service";

export async function GET(request: Request) {
  const { authorized, school_id } = await verifySchoolAdmin();
  if (!authorized) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(request.url);
  const classId = searchParams.get("class_id");

  const supabase = getServiceClient();
  const { data: school } = await supabase.from("schools").select("name, logo_url").eq("id", school_id).single();
  const { data: activeTerm } = await supabase.from("academic_terms").select("name, session_id").eq("school_id", school_id).eq("is_active", true).maybeSingle();

  let sessionName = "";
  if (activeTerm?.session_id) {
    const { data: s } = await supabase.from("academic_sessions").select("name").eq("id", activeTerm.session_id).single();
    sessionName = s?.name || "";
  }

  let query = supabase.from("students").select("*, profiles(full_name, email)").eq("school_id", school_id).order("created_at");
  if (classId) query = query.eq("class_id", classId);
  const { data: students } = await query;

  let className = "All Classes";
  if (classId) {
    const { data: cls } = await supabase.from("classes").select("name").eq("id", classId).single();
    className = cls?.name || "Unknown";
  }

  const sorted = [...(students || [])].sort((a: any, b: any) => (a.profiles?.full_name || "").localeCompare(b.profiles?.full_name || ""));

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Student Credentials - ${className}</title>
<style>
  body { font-family: Inter, sans-serif; padding: 40px; color: #16202e; }
  .header { text-align: center; margin-bottom: 30px; }
  .header img { max-height: 60px; margin-bottom: 10px; }
  .header h1 { font-size: 22px; margin: 4px 0; color: #2a4b8d; }
  .header p { font-size: 13px; color: #4b5666; margin: 2px 0; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #2a4b8d; color: #fff; padding: 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #e2e5ea; }
  tr:nth-child(even) td { background: #f5f6f8; }
  .footer { text-align: center; margin-top: 30px; font-size: 10px; color: #8891a0; }
  @media print { body { padding: 0; } }
</style></head><body>
<div class="header">
  ${school?.logo_url ? `<img src="${school.logo_url}" alt=""/>` : ""}
  <h1>${school?.name || "School"}</h1>
  <p>Student Login Credentials</p>
  <p>${sessionName} · ${activeTerm?.name || ""} | ${className} | ${sorted.length} students</p>
</div>
<table>
  <thead><tr><th style="width:40px">S/N</th><th>Full Name</th><th>Username (Email)</th><th>Password</th></tr></thead>
  <tbody>
    ${sorted.map((s: any, i: number) => `<tr>
      <td>${i + 1}</td>
      <td>${s.profiles?.full_name || "—"}</td>
      <td style="font-family:monospace;font-size:11px">${s.profiles?.email || "—"}</td>
      <td style="font-family:monospace;font-size:11px">${s.generated_password || "Reset needed"}</td>
    </tr>`).join("")}
  </tbody>
</table>
<div class="footer">Generated by SchoolAid · Print and distribute to students</div>
</body></html>`;

  return new NextResponse(html, { headers: { "Content-Type": "text/html", "Content-Disposition": "attachment; filename=student-credentials.html" } });
}
